server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///F:/native-file-repo
        git:
          uri: https://github.com/sshwn/spring-cloud-config-08.git
#          uri: file:///git-local-repo
#          username: private 일 경우
#          password: priavte 일 경우